name: BK-mainBranch2S3

on:
  push:
    branches:
      - main # トリガーするブランチを指定

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #該当リポジトリのSettingに設定したAWSアクセスキーとシークレットキー
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Archive repository
        run: |
          git archive --format=tar.gz HEAD > XXXXX-main-repository.tar.gz

      - name: Upload to S3
        run: |
          aws s3 cp XXXX-main-repository.tar.gz s3://{Bucket-name}}/{path-name-1}/{repo-name}-$(date +%Y%m%d%H%M%S).tar.gz