name: Deploy Debug

on:
  workflow_dispatch:
    inputs:
      deploy_gate_message:
        description: "Deploy Gateに送信するメッセージ"
        required: false
        type: string

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    environment:
      name: DEBUG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set properties
        run: |
          echo ACCESS_KEY=${{ secrets.ACCESS_KEY }} >> ./local.properties
          echo SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} >> ./local.properties
          echo DIRECTORY_NAME=${{ secrets.DIRECTORY_NAME }} >> ./local.properties
          echo DEBUG_BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> ./local.properties
          echo DEBUG_BUCKET_BASE_URL=${{ secrets.BUCKET_BASE_URL }} >> ./local.properties

      - name: Set Amplify configuration
        env:
          JSON_DECODE: ${{ secrets.AMPLIFY_CONFIGURATION_BASE64_ENCODE }}
        run: |
          echo $JSON_DECODE | base64 --decode > app/src/main/res/raw/amplifyconfiguration.json

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Set APP VERSION
        id: app_version
        run: |
          VERSION=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+.[0-9]+')
          echo APP_VERSION=$VERSION >> $GITHUB_OUTPUT

      - name: Rename output file
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-${{ steps.app_version.outputs.APP_VERSION }}.apk

      - name: Deploy to DeployGate
        run: |
          curl --url "https://deploygate.com/api/users/${{ secrets.DEPLOY_GATE_USER_NAME }}/apps" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_GATE_API_KEY }}" \
          -X POST \
          -F "file=@app/build/outputs/apk/debug/app-${{ steps.app_version.outputs.APP_VERSION }}.apk" --form-string "message=${{ github.event.inputs.deploy_gate_message }}"

      - name: Upload apk file
        uses: actions/upload-artifact@v4
        with:
          name: android debug apk file
          path: app/build/outputs/apk/debug/app-${{ steps.app_version.outputs.APP_VERSION }}.apk